# Generated by Django 5.2.7 on 2025-11-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
