# Generated by Django 5.2.7 on 2026-02-02 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RO', 'Roads & Potholes'), ('GA', 'Garbage & Waste'), ('UT', 'Utilities (Water/Power)'), ('PB', 'Public Buildings'), ('OT', 'Other')], max_length=2, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('department_head_name', models.CharField(max_length=100)),
                ('department_head_email', models.EmailField(max_length=254)),
                ('department_head_phone', models.CharField(blank=True, max_length=15)),
                ('office_address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Department Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='ASSIGNED', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='complaints.complaint')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complaints.department')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('complaint', 'department')},
            },
        ),
    ]
