# Generated by Django 5.2.7 on 2026-02-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_department_departmentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='original_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='complaints.complaint'),
        ),
    ]
