# Generated by Django 5.2.7 on 2026-03-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_duplicate_detection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'In Progress'), ('R', 'Resolved'), ('D', 'Declined')], default='P', max_length=1),
        ),
    ]
