services:
  - type: web
    name: scfms-web
    runtime: python
    plan: free
    rootDir: scfms_project
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput

    startCommand: daphne -b 0.0.0.0 -p $PORT scfms_backend.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: scfms_backend.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SITE_URL
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: no-reply@scfms.onrender.com
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.filebased.EmailBackend
      - key: DATABASE_URL
        fromDatabase:
          name: scfms-db
          property: connectionString

databases:
  - name: scfms-db
    plan: free
